# docker build -t registry.cn-beijing.aliyuncs.com/windli/robotframework-browser-chromium-base:1.0 -f Dockerfile .
FROM registry.cn-beijing.aliyuncs.com/windli/robotframework-browser-base:1.0
LABEL org.opencontainers.image.authors="yong.li@governance-solutions.com"

RUN env && which npm && rfbrowser init && bash -c 'rm -rf /usr/local/lib/python3*/dist-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/{firefox*,webkit*}'
RUN ln -s /usr/local/lib/python3*/*-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/ /opt/browsers && \
    mkdir -p /root/.cache && \
    ln -s /usr/local/lib/python3*/*-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/ /root/.cache/ms-playwright && \
    ln -s /usr/local/lib/python3*/*-packages/Browser/wrapper/node_modules/.bin/playwright /usr/bin/
